// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB-vMaWOZLzki02zp6bSFjj6_evXVhfq4k',
//     appId: '1:864761509293:web:3d6cd528052d963dbe9d24',
//     messagingSenderId: '864761509293',
//     projectId: 'app-condotop-teste',
//     authDomain: 'app-condotop-teste.firebaseapp.com',
//     storageBucket: 'app-condotop-teste.firebasestorage.app',
//     measurementId: 'G-XHTV1M5KWN',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBu8iNWQxeDULw7gH61eXehtuG98hB1FwE',
//     appId: '1:864761509293:android:abd8a23c7d65ed0bbe9d24',
//     messagingSenderId: '864761509293',
//     projectId: 'app-condotop-teste',
//     storageBucket: 'app-condotop-teste.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBPArEE8OlIa9yy_p03QldJHmFWNLXkIPE',
//     appId: '1:864761509293:ios:b08661625ddbc606be9d24',
//     messagingSenderId: '864761509293',
//     projectId: 'app-condotop-teste',
//     storageBucket: 'app-condotop-teste.firebasestorage.app',
//     iosBundleId: 'com.condotop.app',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBPArEE8OlIa9yy_p03QldJHmFWNLXkIPE',
//     appId: '1:864761509293:ios:b08661625ddbc606be9d24',
//     messagingSenderId: '864761509293',
//     projectId: 'app-condotop-teste',
//     storageBucket: 'app-condotop-teste.firebasestorage.app',
//     iosBundleId: 'com.condotop.app',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyB-vMaWOZLzki02zp6bSFjj6_evXVhfq4k',
//     appId: '1:864761509293:web:890eef11023eb0c8be9d24',
//     messagingSenderId: '864761509293',
//     projectId: 'app-condotop-teste',
//     authDomain: 'app-condotop-teste.firebaseapp.com',
//     storageBucket: 'app-condotop-teste.firebasestorage.app',
//     measurementId: 'G-DKLGQ4SDG5',
//   );

// }